---

- name: Reboot Server
  hosts: hadoopservers
  strategy: free
  gather_facts: false

  tasks:
  - name: To Reboot Server
    shell: /sbin/shutdown -r now
    async: 1
    poll: 0
    
  - name: waiting for serverbooting up
    wait_for_connection:
      delay: 60
      timeout: 300
