---

- name: Update and Install Some Packages
  hosts: hadoopservers
  strategy: free
  gather_facts: false

  tasks:
  - name: Update All Linux Pkg Latest
    yum:
      name: '*'
      # Latest son versionu anlamına geliyor, present derken illa son version'u kurmuş olmayabilirsiniz.
      state: latest
  
  - name: Install or Sure Wget Installed 
    yum:
      name: wget
      state : installed
      # Çokca present kullanılıyor farklılık olsun diye 'installed kullandım'

  - name: Install Chrony kind a NTP Implamentation
    yum:
      name: chrony
      state: installed

  - name: Install git for Docker Implamentation
    yum:
      name: git
      state: installed

  - name: Install net-tools for Cli Debug Needs
    yum:
      name: net-tools
      state: installed
