---

- name: Enable disable or provider autmatic service start when OS reboot
  hosts: hadoopservers
  gather_facts: false

  tasks:
  - name: Disable Firewalld Service For Startup
    service:
      name: firewalld
      enabled: no
      # enabled no for disable service

  - name: Stop Firewalld Service
    service:
      name: firewalld
      state: stopped
      # use stopped to stop service  